AWSTemplateFormatVersion: 2010-09-09

Resources:
  roleECRAccess:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
          -
            PolicyName: ECRAccesss
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                -
                  Effect: Allow
                  Action: ecr:*
                  Resource:
                    - "*"
  ECRInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - Ref: roleECRAccess

  AppInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-west-2a
      ImageId: ami-086b16d6badeb5716
      InstanceType: t2.micro
      KeyName: aws_go_app
      SecurityGroups:
         - !Ref AppSecurityGroup
      Tags:
        - Key: Name
          Value: cloudformation-app
      IamInstanceProfile:
        Ref: ECRInstanceProfile
      UserData:
        Fn::Base64: |
          #!/bin/bash
          sudo yum update -y
          sudo yum install -y docker
          sudo yum install -y git aws-cli
          sudo service docker start
          sudo usermod -a -G docker ec2-user
          aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 121901806849.dkr.ecr.us-west-2.amazonaws.com
          docker run -p 5000:5000 -d 121901806849.dkr.ecr.us-west-2.amazonaws.com/go-hostname:latest
          docker run -p 80:80 -d 121901806849.dkr.ecr.us-west-2.amazonaws.com/nginx-go-hostname:latest

  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: cloudformation-group
      GroupName: cloudformation-group
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80